	<strong>Initiatives</strong>
<ul style="text-align:justify">
	<li>
		Led development of Big and Smart Data MS certificate program starting Aug. 2014 at Wright State University.
	</li>
	<li>
		On the steering committee of the New Media Institute, approved starting fall 2000. It is a campus-wide initiative covering many disciplines.
	</li>
	<li>
		On the steering committee of Masters in Internet Technology program, expected to be approved starting fall 2000. An interdisciplinary professional degree program proposed by Management Sciences (Business School), Computer Science, and School of Journalism.
	</li>
	
</ul>

<br>
<p>
	<strong>New Courses Defined/Offered</strong>
</p>
<ul style="text-align:justify">
	<li>
		<strong>Advanced Topics in Semantic Web</strong>, CS 7820, offered at Wright State University Fall 2013 and Fall 2016.
	</li>
	
	<ul>
		<li>
			This course is about the Semantic Web, a key enabler of Web 3.0. It goes beyond the recent language standards of RDF and OWL to understand new techniques, technologies and algorithms for making a broad variety of data meaningful and more amenable to processing by humans and machines (on the Web, as Web services, generated on social networks or generated by sensors and mobile devices). Topics covered include research in semantic search, browsing, integration, analysis and discovery.
		</li>

                <li>Additional information: lecture videos (<a href="https://www.youtube.com/watch?v=yKBNcjyjqg4&list=PLqJzTtkUiq56-xNVT7G6Ee9eGSFHLkFzE">Fall 2016</a>).</li>

	</ul>
	
	<li>
		<strong>Semantic, Cognitive, and Perceptual Computing</strong>, offered at Wright State University Summer 2016.
	</li>
	
	<ul>
		<li>
			Additional information: <a href="https://www.youtube.com/playlist?list=PLqJzTtkUiq54DDEEZvzisPlSGp_BadhNJ">lecture videos</a>.
		</li>
	</ul>
	
	<li>
		<strong>Web Information Systems</strong>, CS 4800/6800/7900, offered at Wright State University Fall 2010, Fall 2012, Spring 2015, and Spring 2016.
	</li>

	<ul>
		<li>
			Covers topics in building Web-based applications involving variety of data; covers data, metadata, knowledge and ontologies; key Web languages and protocols; search engines, social networking, Web2.0, semantic web. Good programming skills are prerequisite.
		</li>

		<li>
			Additional information: course pages (<a href="http://knoesis.org/?q=cs4800-6800-spring2016">Spring 2016</a>, <a href="http://knoesis.org/?q=courses/cs4800-6800">Fall 2012</a>); lecture videos (<a href="https://www.youtube.com/playlist?list=PL1599D16BE401C35A">Fall 2010</a>, <a href="https://www.youtube.com/playlist?list=PLA7CE8FC357B7BB96">Spring 2012</a>).
		</li>
	</ul>	

	<li>
		<strong>Web 3.0: Next Gen Web &amp; Apps</strong>, CS 7900, offered at Wright State University Spring 2013, Fall 2014, and Fall 2015. 
		<ul>
			<li>
				Additional information: <a href="http://knoesis.org/web3cs7900">course page</a>, lecture videos (<a href="https://www.youtube.com/playlist?list=PLqJzTtkUiq550R-Q8IRXlobvrn9_g-MZP">Fall 2015</a>, <a href="https://www.youtube.com/playlist?list=PLqJzTtkUiq57IolxiyOgE8DgzJYipEcsz">Spring 2013</a>).
				</li>
		</ul>
	
	<li>
		<strong>Semantics-empowered Web 3.0</strong>, CS 4800/6800, offered at Wright State University Fall 2012.
	</li>
	<li>
		<strong>Information Integration and Analysis</strong>, CS 790-03, offered at Wright State University starting Spring Quarter 2007.
	</li>
	<li>
		<strong>Semantic Web Services and Processes</strong>, CSCI 8351, defined and offered spring 2004, (formerly Semantic Enterprise, defined and offered Fall 2002). 
		<ul>
			<li>
			For advanced graduate students, the earliest offering of a course on this topic in the world.
			</li>
		</ul>
	</li>
	<li>
		<strong>Semantic Web</strong>, defined and offered spring 2002. 
		<ul>
			<li>
			For advanced graduate students, one of the earliest offerings of a course on this topic in the world.
			</li>
		</ul>
	</li>
	<li>
		<strong>Global Information Systems: Promises and Challenges</strong>, defined and offered since 1995. 
		<ul>
			<li>
			For Computer Science seniors and graduate students; often taken by students in other disciplines. One of the earliest Internet-based courses, with innovative mix of internet technologies and information systems.
			</li>
		</ul>
	</li>

	<li>
		<strong>Enterprise Integration</strong>, defined and offered from 1995 to 2000. 
	</li>	
    <ul>		
		<li>	
			A one-of-a-kind course for computer science graduate students, sometimes taken by students in management.
			Covers issues in complex enterprise-wide solutions in the real world. Main emphasis is on distributed computing and information systems and e-commerce
			technologies, but also shares real-world experiences.
		</li>
	</ul>
	
	<li>
		<strong>Internet Programming</strong>, 2000. For the new Masters in Internet Technology program.
	</li>
	
		<li>
		<strong>Internet Information Systems</strong>, 2000. For the new Masters in Internet Technology program.
	</li>	
</ul>	
	
	
	
	
<!-- OUTDATED
	<li>
		<strong>Advanced Topics in Semantic Web</strong>, CS 79950, offered at Wright State University Fall 2013.
	</li>

	<li>
		<strong>Web 3.0: Next Generation Web &amp; Apps</strong>, CS 7900, offered at Wright State University Spring 2013.
	</li>

	<li>
		<strong>Semantics empowered Web 3.0</strong>, CS4800/6800, offered at Wright State University Fall 2012.
	</li>

	<li>
		<strong>Information Integration and Analysis</strong>, CS 790-03, offered at Wright State University starting Spring Quarter 2007.
	</li>

	<li>
		<strong>Semantic Web Services and Processes</strong>, CSCI 8351, defined and offered spring 2004, (formerly Semantic Enterprise, defined and offered Fall 2002). For advanced graduate students, the
		earliest offering of a course on this topic in the world.
	</li>

	<li>
		<strong>Semantic Web</strong>, defined and offered spring 2002. For advanced graduate students, one of the earliest offerings of a course on this topic in the world.
	</li>

	<li>
		<strong>Global Information Systems: Promises and Challenges</strong>, defined and offered since 1995. For Computer Science seniors and graduate students; often taken by students in other disciplines. One of the earliest Internet-based courses, with innovative mix of internet technologies and information systems.
	</li>

	<li>
		<strong>Enterprise Integration</strong>, defined and offered from 1995 to 2000. A one-of-a-kind course for Computer Science graduate students, sometimes taken by students in management.
		Covers issues in complex enterprise-wide solutions in the real world. Main emphasis is on distributed computing and information systems and e-commerce
		technologies, but also shares real-world experiences.
	</li>

	<li>
		<strong>Internet Programming</strong>, 2000. For the new Masters in Internet Technology program.
	</li>

	<li>
		<strong>Internet Information Systems</strong>, 2000. For the new Masters in Internet Technology program.
	</li>

</ul>

<br>
<p>
	<strong>External Curriculum Advising/Accreditation:</strong>
</p>
<ul>
	<li>
		Program Evaluator/Accreditation Visitor for the Computer Sciences Accreditation Board (sponsored by IEEE and ACM), 1993&ndash;1998.
	</li>
	
</ul>
-->
