<style>
p {
	line-height: 1.45em;
}
</style>

<h3>On Relationships-centric Views of Semantics: A Brief Research Review</h3>
<p>
"<strong style="font-style:italic">The process of tying two items together is the important thing.</strong>" -Vannevar Bush, in his seminal article, As we may think  (the Atlantic Monthly, July 1945). He pointed out the inadequacy of contemporary indexing systems at mimicking the "natural" way we as humans seek out information. He stressed that the human mind worked by <strong style="font-style:italic">association</strong>. "<span style="font-style:italic">It</span> [the brain] <span style="font-style:italic">operates by association. With one item in its grasp, it snaps instantly to the next that is suggested by the association...</span>" he added.
</p>

<p>Two decades of our research on semantics of information has been influenced by the importance of relationships as underlined by Dr. Bush and several others visionaries (e.g., William Woods' "What's in a Link" [<a href="http://citeseer.ist.psu.edu/context/89993/0">Woods1975</a>]).  We have recognized that relationships are at the heart of semantics [<a href="http://www.sofsem.cz/sofsem02/keynote.html">Sheth2002</a>], observed the changing focus from documents to entities and on to relationships [<a href="http://www.cs.uic.edu/~ifc/SWDB/keynote-as.html">Sheth2003</a>], and have investigated broad variety of issues related to modeling, validating, discovering and exploiting various types of relationships between entities in content [<a href="http://citeseer.ist.psu.edu/context/2471976/0">Sheth+2003</a>].
</p>

<p>
Our earliest focus on relationships was in terms of mappings to deal with semantic heterogeneity to achieve semantic interoperability and schema integration [<a href="http://portal.acm.org/citation.cfm?id=96602.96604">Sheth-Larson1990</a>, <a href="http://portal.acm.org/citation.cfm?id=653395">Sheth+1988</a>, <a href="http://lsdis.cs.uga.edu/library/download/SM94.pdf">BERDI</a>]. Over a decade ago, we introduces a comprehensive definition of <span style="text-decoration:underline">semantic proximity</span> [<a href="http://citeseer.ist.psu.edu/sheth92so.html">Sheth-Kashyap 92</a>, <a href="http://www.springerlink.com/media/HB5CYPVGQQ5KDYVNYD9L/Contributions/K/1/R/A/K1RA34FF17RR6W8X.pdf">Kashyap-Sheth 96</a>] to address the difficulty in modeling a notion that is also termed semantic similarity or semantic distance. <a href="http://www.semagix.com/documents/SEII.pdf">Semantic metadata</a> is key to both the semantic Web and techniques that support semantic relationships.  An early work on <span style="text-decoration:underline">domain specific metadata</span> annotation and search, which led to the earliest commercial product of this type (from Bellcore in 1995) came from our InfoHarness systems [<a href="http://www.cs.rutgers.edu/~shklar/papers/listing/caise95.pdf">Shklar+1995</a>] [<a href="http://citeseer.ist.psu.edu/shah99infoharness.html">Shah-Sheth99</a>].  

<br><br>

The VisualHarness system extended that work beyond textual data to include image data [<a href="http://lsdis.cs.uga.edu/library/download/SS98.doc">Sheth+1999</a>].  In 1996, we introduced the concept of MREF (<span style="text-decoration:underline"><strong>M</strong>etadata <strong>REF</strong>erence link</span>) for associating semantic metadata on physical links represented using HREF [<a href="http://lsdis.cs.uga.edu/library/download/SK96.pdf">Sheth-Kashyap1996</a>, <a href="http://portal.acm.org/citation.cfm?id=582987.785925">Shah-Sheth1998</a>].  This proposal seeks to realize a second generation of semantic relationships.  As we realized that a single ontology would not be able to capture domain/conceptual models necessary to capture the semantics and agreements, we investigated inter-ontological relationships in our information brokering work [<a href="#">Kashyap-Sheth1994</a>] and <span style="text-decoration:underline">multi-ontology query processing</span> in the OBSERVER system [<a href="http://citeseer.ist.psu.edu/311175.html">Mena+1996</a>] [<a href="http://citeseer.ist.psu.edu/mena00imprecise.html">Mena+2000</a>].  In the InfoQuilt system, we defined IScapes, a paradigm for validating <span style="text-decoration:underline">complex relationships</span> defined using multiple ontologies over heterogeneous Web-based data [<a href="http://citeseer.ist.psu.edu/context/2560893/0">Sheth+2002a</a>]. Our most recent work on complex relationships is called <span style="text-decoration:underline">Semantic Associations</span> [<a href="http://portal.acm.org/citation.cfm?id=637418">Anyanwu-Sheth03</a>].  

<br><br>

In this work, we create large RDF graph of metadata of heterogeneous data, and <span style="text-decoration:underline">discover semantic associations</span>.  The work covers main memory RDF query processing, algorithms for finding paths, and for ranking semantic associations [<a href="http://portal.acm.org/citation.cfm?id=1060745.1060766">Anyanwu+05</a>] [<a href="http://csdl2.computer.org/persagen/DLAbsToc.jsp?resourcePath=/dl/mags/ic/&amp;toc=comp/mags/ic/2005/03/w3toc.xml&amp;DOI=10.1109/MIC.2005.63">Aleman-Meza+2005</a>].  Compared to document ranking, ranking relationships is significantly more challenging.  The concept of <span style="text-decoration:underline">Active Semantic Documents</span> (<a href="http://lsdis.cs.uga.edu/projects/asdoc/index.php?page=2">ASD</a>) make documents actionable.  ASD involve automatic lexical and semantic annotation of documents and the automatic evaluation of rules applicable to the annotations, with the ability to take appropriate actions (e.g. see application to electronic medical records).  

<br><br>

Our research on semantics, where relationships play critical role has led to commercial products on <span style="text-decoration:underline">semantic search</span> [<a href="http://smw.internet.com/gen/reviews/searchassociation/index.html">Townley2000</a>] and on Enterprise Semantic Application platform [<a href="http://portal.acm.org/citation.cfm?id=613729">Sheth+2002</a>], including <span style="text-decoration:underline">automatic semantic metadata extraction</span> (also terms metadata annotation) technology [<a href="http://lsdis.cs.uga.edu/library/download/HSK02-SEE.pdf">Hammond+2002</a>].  The latter could process one million Web pages per hour per traditional server performing deep ontology-driven metadata extraction, while IBM's WebFountain related technology has demonstrated more scalable but shallower metadata extraction resulting into annotation of over 4 billion pages [<a href="http://citeseer.ist.psu.edu/dill03semtag.html">Brill+2003</a>]. Many research projects as well as deployed enterprise applications have resulted using these technologies, some of which are reported in [<a href="http://www.springerlink.com/media/AF8ALTNQYHCWTM4HWKAK/Contributions/R/5/6/T/R56TJFYKF9HTJ09W.pdf">Aleman-Meza+2005b</a>, <a href="http://www.igi-online.com/downloads/pdf/ITJ2672_aQVKbTJVJd.pdf">Sheth+2005a</a>, <a href="http://lsdis.cs.uga.edu/library/download/Sheth05-IASW-invited-Fin2.pdf">Sheth2005</a>].
</p>
<p>
In most of the examples in his article Dr. Bush describes what we term as <span style="font-style:italic">implicit relationships</span>. We believe that there is a lot of merit in the use of <span style="font-style:italic">explicit named relationships</span> for the purpose of resource organization. Extracting such relationships from documents has received considerable interest in the field of computational linguistics and information retrieval. Despite a few decades of research this problem remains a very hard problem to solve. One outcome of our research thus far is our ability to create large instance bases for ontologies from multiple trusted sources [<a href="http://www.wilshireconferences.com/STC05/AGENDA/A11B.htm">Sheth2004</a>]. We have created many populated ontologies in academic and commercial settings in which schemas are populated with corresponding knowledge bases containing multi-million entity instances and relationship instances linking these entities (some of these are being made publicly available, e.g., <a href="http://lsdis.cs.uga.edu/projects/semdis/sweto/">SWETO</a>, <a href="http://lsdis.cs.uga.edu/projects/glycomics/glyco/">GlycO</a>, <a href="http://lsdis.cs.uga.edu/projects/glycomics/propreo/">ProPreO</a>, while the technologies such as Semagix Freedom have been use to create focused domain ontologies with as many as 14 million entity instances).  Such populated ontologies significantly enhance our ability to identify potential relationships from unstructured data as well as from distributed information resources.
</p>
<p>Several voices have questioned the viability, reliance and adequacy of formal ontologies.  One perspective is represented by Google's Peter Norvig (see <a href="http://www.alwayson-network.com/comments.php?id=7480_0_3_0_C">AOblog</a>) that questions viability of the Semantic Web because creating domain ontologies is considered as impractical, which we have rebutted (see <a href="http://lsdis.cs.uga.edu/~amit/blog/index.php?title=semantic_web_a_different_perspective_on&amp;more=1&amp;c=1&amp;tb=1&amp;pb=1">ShethBlog</a>)..  An insightful view, that of (in-)adequacy of crisp logics for question-answering system (which demands far more than Web search engines) is that of Lotfi Zadeh [<a href="http://www.springerlink.com/media/EF6LWLMWXR3NC3K5YJ2Q/Contributions/N/M/J/2/NMJ254VEGU0DFYN3.pdf">Zadeh2003</a>]. More recently, we have explored the dimension of implicit, formal and powerful semantic representations [<a href="http://www.informatik.uni-trier.de/~ley/db/journals/ijswis/ijswis1.html#ShethRT05">Sheth+2005b</a>], and investigated uses of formal and semi-formal ontologies [<a href="ftp://ftp.research.microsoft.com/pub/debull/A03dec/sheth1.ps">Sheth-Ramakrishnan2003</a>].  When focusing on deep domain semantics in biology (e.g. GlycO and ProPreO) we explored the need to have more expressive probabilistic modeling of relationships, involved semantic annotation of scientific experiment data (in addition to textual) and integrated discovery over scientific literature and scientific experiment results.
</p>
<p>
Amit Sheth, September 2005
</p>

